language: php

services:
  - rabbitmq

php:
  - 7.2
  - 7.3
  - 7.4
  - 8.0

env:
  matrix:
    - DEPENDENCIES="dev"
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: 8.0

before_install:
  - composer self-update
  - composer clear-cache
  
install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" = 'high' ]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable; fi
  - if [ "$DEPENDENCIES" = 'low' ]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable --prefer-lowest; fi

script:
   - bin/phpspec run --format=pretty
   - bin/phpunit --verbose
