language: php

services:
  - rabbitmq

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  matrix:
    - DEPENDENCIES="dev"
    - DEPENDENCIES="high"
    - DEPENDENCIES="low"

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: 7.0
    - php: 7.1

before_install:
  - composer self-update
  - composer clear-cache
  
install:
  - export COMPOSER_ROOT_VERSION=dev-master
  - if [ "$DEPENDENCIES" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi;
  - if [ "$DEPENDENCIES" = 'high' ]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable; fi
  - if [ "$DEPENDENCIES" = 'low' ]; then travis_retry composer update --no-interaction --no-ansi --no-progress --no-suggest --optimize-autoloader --prefer-stable --prefer-lowest; fi

before_script:
  - echo "<?php if (PHP_VERSION_ID >= 50400) echo ',@php5.4';" > php_version_tags.php

script:
   - bin/phpspec run --format=pretty
   - bin/phpunit --verbose
   #- ./vendor/bin/behat --format=pretty --tags '~@php-version'`php php_version_tags.php`
